openapi: 3.0.3
info:
  title: Smarbar Backoffice AP
  description: Smarbar Backoffice AP
  version: 1.0.0
paths:
  /categories:
    get:
      operationId: getAllCategories
      responses:
        200:
          description: Entity successfully get
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/category"
    post:
      operationId: createCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        201:
          $ref: "#/components/responses/201"
  /categories/{categoryId}:
    parameters:
      - name: categoryId
        in: path
        required: true
        schema:
          type: string
    put:
      operationId: updateCategory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/category"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteCategory
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getCategoryById
      responses:
        200:
          description: Entity successfully get
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/category"
  /articles:
    get:
      operationId: getAllArticles
      responses:
        200:
          description: Entity successfully get
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/article"
    post:
      operationId: createArticle
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/article"
      responses:
        201:
          $ref: "#/components/responses/201"
  /articles/{articleId}:
    parameters:
      - name: articleId
        in: path
        required: true
        schema:
          type: string
    put:
      operationId: updateArticle
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/article"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteArticle
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getArticleById
      responses:
        200:
          description: Entity successfully get
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/article"
  /tables:
    get:
      operationId: getAllTables
      responses:
        200:
          description: Entity successfully get
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/table"
    post:
      operationId: createTable
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/table"
      responses:
        201:
          $ref: "#/components/responses/201"
  /tables/{tableId}:
    parameters:
      - name: tableId
        in: path
        required: true
        schema:
          type: string
    put:
      operationId: updateTable
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/table"
      responses:
        200:
          description: Entity successfully updated
    delete:
      operationId: deleteTable
      responses:
        200:
          description: Entity successfully deleted
    get:
      operationId: getTableById
      responses:
        200:
          description: Entity successfully get
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/table"
components:
  schemas:
    category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
    article:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
        description:
          type: string
        picture:
          type: string
    table:
      type: object
      properties:
        name:
          type: string
        seatCount:
          type: integer
          format: int32
        active:
          type: boolean
  responses:
    201:
      description: Entity successfully created
      headers:
        location:
          description: Entity successfully created
          schema:
            type: string
            format: uri